version: "3.8"
services:
  python:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../app:/usr/src/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
